# mysql-statefulset.yml
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
# Я використовую Secret 'mysql-auth' та ConfigMap 'mysql-init-sql'
# для сумісності з логікою ініціалізації БД.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS todo;
    GRANT ALL PRIVILEGES ON todo.* TO 'appuser'@'%' IDENTIFIED BY 'apppass';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  selector: { app: mysql }
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
# Ваш StatefulSet з інтегрованими правилами
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # === БЛОК ПЛАНУВАННЯ (Вимога 5) ===
      # 5.1. Toleration: може працювати на нодах з Taint app=mysql:NoSchedule
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "mysql"
        effect: "NoSchedule"
      affinity:
        # 5.3. Required Node Affinity: розміщувати лише на нодах app=mysql
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values: ["mysql"]
        # 5.2. Required Pod Anti-Affinity: не розміщувати на одній ноді
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["mysql"]
            topologyKey: kubernetes.io/hostname
      # =================================
      containers:
      - name: mysql
        image: mysql:8.0
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        # Використовуємо 'mysql-auth' Secret та 'todo' DB name для сумісності
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: todo
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          # subPath: mysql (видалено, стандартно не використовується для PV/PVC)
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          tcpSocket: { port: 3306 } # Проби змінено на tcpSocket для KIND
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 3306 } # Проби змінено на tcpSocket для KIND
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: config-map
        configMap:
          name: mysql-init-sql # Назва ConfigMap для ініціалізації
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi